/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReportRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "VALIDATOR_STAKE"
      | "bountyVault"
      | "finalizeReport"
      | "hasVoted"
      | "owner"
      | "renounceOwnership"
      | "reportCount"
      | "reports"
      | "reputation"
      | "stakes"
      | "submitReport"
      | "transferOwnership"
      | "validateReport"
      | "validatorVotes"
      | "withdrawSlashedStakes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReportResolved"
      | "ReportSubmitted"
      | "ReportValidated"
      | "StakeSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "VALIDATOR_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bountyVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeReport",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reports",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReport",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateReport",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorVotes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSlashedStakes",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "VALIDATOR_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bountyVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reports", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSlashedStakes",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportResolvedEvent {
  export type InputTuple = [reportId: BigNumberish, status: BigNumberish];
  export type OutputTuple = [reportId: bigint, status: bigint];
  export interface OutputObject {
    reportId: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportSubmittedEvent {
  export type InputTuple = [
    reportId: BigNumberish,
    bountyId: BigNumberish,
    reporter: AddressLike,
    ipfsHash: string
  ];
  export type OutputTuple = [
    reportId: bigint,
    bountyId: bigint,
    reporter: string,
    ipfsHash: string
  ];
  export interface OutputObject {
    reportId: bigint;
    bountyId: bigint;
    reporter: string;
    ipfsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportValidatedEvent {
  export type InputTuple = [
    reportId: BigNumberish,
    validator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    reportId: bigint,
    validator: string,
    approved: boolean
  ];
  export interface OutputObject {
    reportId: bigint;
    validator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeSettledEvent {
  export type InputTuple = [
    reportId: BigNumberish,
    validator: AddressLike,
    amount: BigNumberish,
    refunded: boolean
  ];
  export type OutputTuple = [
    reportId: bigint,
    validator: string,
    amount: bigint,
    refunded: boolean
  ];
  export interface OutputObject {
    reportId: bigint;
    validator: string;
    amount: bigint;
    refunded: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReportRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReportRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReportRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  VALIDATOR_STAKE: TypedContractMethod<[], [bigint], "view">;

  bountyVault: TypedContractMethod<[], [string], "view">;

  finalizeReport: TypedContractMethod<
    [reportId: BigNumberish, gasCompensation: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reportCount: TypedContractMethod<[], [bigint], "view">;

  reports: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        bountyId: bigint;
        reporter: string;
        ipfsHash: string;
        status: bigint;
        approvals: bigint;
        rejections: bigint;
      }
    ],
    "view"
  >;

  reputation: TypedContractMethod<[], [string], "view">;

  stakes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  submitReport: TypedContractMethod<
    [bountyId: BigNumberish, ipfsHash: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validateReport: TypedContractMethod<
    [reportId: BigNumberish, approve: boolean],
    [void],
    "payable"
  >;

  validatorVotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  withdrawSlashedStakes: TypedContractMethod<
    [_to: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "VALIDATOR_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bountyVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalizeReport"
  ): TypedContractMethod<
    [reportId: BigNumberish, gasCompensation: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reports"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        bountyId: bigint;
        reporter: string;
        ipfsHash: string;
        status: bigint;
        approvals: bigint;
        rejections: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitReport"
  ): TypedContractMethod<
    [bountyId: BigNumberish, ipfsHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validateReport"
  ): TypedContractMethod<
    [reportId: BigNumberish, approve: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "validatorVotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawSlashedStakes"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReportResolved"
  ): TypedContractEvent<
    ReportResolvedEvent.InputTuple,
    ReportResolvedEvent.OutputTuple,
    ReportResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ReportSubmitted"
  ): TypedContractEvent<
    ReportSubmittedEvent.InputTuple,
    ReportSubmittedEvent.OutputTuple,
    ReportSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ReportValidated"
  ): TypedContractEvent<
    ReportValidatedEvent.InputTuple,
    ReportValidatedEvent.OutputTuple,
    ReportValidatedEvent.OutputObject
  >;
  getEvent(
    key: "StakeSettled"
  ): TypedContractEvent<
    StakeSettledEvent.InputTuple,
    StakeSettledEvent.OutputTuple,
    StakeSettledEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReportResolved(uint256,uint8)": TypedContractEvent<
      ReportResolvedEvent.InputTuple,
      ReportResolvedEvent.OutputTuple,
      ReportResolvedEvent.OutputObject
    >;
    ReportResolved: TypedContractEvent<
      ReportResolvedEvent.InputTuple,
      ReportResolvedEvent.OutputTuple,
      ReportResolvedEvent.OutputObject
    >;

    "ReportSubmitted(uint256,uint256,address,string)": TypedContractEvent<
      ReportSubmittedEvent.InputTuple,
      ReportSubmittedEvent.OutputTuple,
      ReportSubmittedEvent.OutputObject
    >;
    ReportSubmitted: TypedContractEvent<
      ReportSubmittedEvent.InputTuple,
      ReportSubmittedEvent.OutputTuple,
      ReportSubmittedEvent.OutputObject
    >;

    "ReportValidated(uint256,address,bool)": TypedContractEvent<
      ReportValidatedEvent.InputTuple,
      ReportValidatedEvent.OutputTuple,
      ReportValidatedEvent.OutputObject
    >;
    ReportValidated: TypedContractEvent<
      ReportValidatedEvent.InputTuple,
      ReportValidatedEvent.OutputTuple,
      ReportValidatedEvent.OutputObject
    >;

    "StakeSettled(uint256,address,uint256,bool)": TypedContractEvent<
      StakeSettledEvent.InputTuple,
      StakeSettledEvent.OutputTuple,
      StakeSettledEvent.OutputObject
    >;
    StakeSettled: TypedContractEvent<
      StakeSettledEvent.InputTuple,
      StakeSettledEvent.OutputTuple,
      StakeSettledEvent.OutputObject
    >;
  };
}
