// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IBountyVault$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBountyVault";
  readonly sourceName: "contracts/interfaces/IBountyVault.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"bountyId","type":"uint256"}],"name":"getReward","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"bountyId","type":"uint256"}],"name":"lockReward","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"uint256","name":"bountyId","type":"uint256"},{"internalType":"address","name":"reporter","type":"address"},{"internalType":"uint256","name":"gasCompensation","type":"uint256"}],"name":"releaseReward","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IBountyVault.sol";
  readonly buildInfoId: "solc-0_8_28-558b657aa3bd51c713d89b77b4d3d625162f11e1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IBountyVault"]: IBountyVault$Type;
    ["contracts/interfaces/IBountyVault.sol:IBountyVault"]: IBountyVault$Type;
  }
}