/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IBountyVaultInterface extends Interface {
  getFunction(
    nameOrSignature: "getReward" | "lockReward" | "releaseReward"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseReward",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockReward", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseReward",
    data: BytesLike
  ): Result;
}

export interface IBountyVault extends BaseContract {
  connect(runner?: ContractRunner | null): IBountyVault;
  waitForDeployment(): Promise<this>;

  interface: IBountyVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReward: TypedContractMethod<[bountyId: BigNumberish], [bigint], "view">;

  lockReward: TypedContractMethod<[bountyId: BigNumberish], [void], "payable">;

  releaseReward: TypedContractMethod<
    [
      bountyId: BigNumberish,
      reporter: AddressLike,
      gasCompensation: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReward"
  ): TypedContractMethod<[bountyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockReward"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "releaseReward"
  ): TypedContractMethod<
    [
      bountyId: BigNumberish,
      reporter: AddressLike,
      gasCompensation: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
