// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IReputation$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IReputation";
  readonly sourceName: "contracts/interfaces/IReputation.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"validator","type":"address"}],"name":"canValidate","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"validator","type":"address"}],"name":"decrease","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"validator","type":"address"}],"name":"increase","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IReputation.sol";
  readonly buildInfoId: "solc-0_8_28-558b657aa3bd51c713d89b77b4d3d625162f11e1";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IReputation"]: IReputation$Type;
    ["contracts/interfaces/IReputation.sol:IReputation"]: IReputation$Type;
  }
}