/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBountyVault,
  IBountyVaultInterface,
} from "../../../contracts/interfaces/IBountyVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "getReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
    ],
    name: "lockReward",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "reporter",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "gasCompensation",
        type: "uint256",
      },
    ],
    name: "releaseReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBountyVault__factory {
  static readonly abi = _abi;
  static createInterface(): IBountyVaultInterface {
    return new Interface(_abi) as IBountyVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBountyVault {
    return new Contract(address, _abi, runner) as unknown as IBountyVault;
  }
}
