/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReputation,
  IReputationInterface,
} from "../../../contracts/interfaces/IReputation";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
    ],
    name: "canValidate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
    ],
    name: "decrease",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "validator",
        type: "address",
      },
    ],
    name: "increase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReputation__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationInterface {
    return new Interface(_abi) as IReputationInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IReputation {
    return new Contract(address, _abi, runner) as unknown as IReputation;
  }
}
